<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 candlestick.gltf --transform
-->

<script>
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf } from "@threlte/extras";

  export const ref = new Group();

  const candlestick = useGltf("/candlestick-transformed.glb", {
    useDraco: true,
  });

  const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await candlestick}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.01}>
      <T.DirectionalLight
        intensity={0.7}
        decay={2}
        rotation={[-0.51, 0.63, 0.76]}
      />
      <T.PerspectiveCamera
        makeDefault={false}
        far={100000}
        near={70}
        fov={45}
        position={[25.6, 242.36, 435.43]}
        rotation={[0.13, 0.05, -0.01]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_3.geometry}
        material={gltf.nodes.Cube_3.material}
        position={[0.95, -98.59, -10.42]}
        scale={[1, 1, 0.17]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_2.geometry}
        material={gltf.nodes.Cube_2.material}
        position={[0.95, 379.31, -10.88]}
        scale={[1, 1, 0.17]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube.geometry}
        material={gltf.nodes.Cube.material}
        position={[0.95, 140.83, -10.42]}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
