<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 model2.gltf --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/model2-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[0, 0.52, 0]} scale={0.1}>
      <T.Mesh geometry={gltf.nodes.Circle001.geometry} material={gltf.materials['Frame.001']} />
      <T.Mesh geometry={gltf.nodes.Circle001_1.geometry} material={gltf.materials['Frame.001']} />
      <T.Mesh geometry={gltf.nodes.Circle001_2.geometry} material={gltf.materials.HeadPhoneHole} />
      <T.Mesh geometry={gltf.nodes.Circle001_3.geometry} material={gltf.materials.USB_C_INSIDE} />
      <T.Mesh geometry={gltf.nodes.Circle001_4.geometry} material={gltf.materials['Frame.001']} />
      <T.Mesh geometry={gltf.nodes.Circle001_5.geometry} material={gltf.materials.TouchbarBorder} />
      <T.Mesh geometry={gltf.nodes.Circle001_6.geometry} material={gltf.materials.Keyboard} />
      <T.Group position={[0, -0.51, 0]} scale={5.8}>
        <T.Mesh geometry={gltf.nodes.Circle006.geometry} material={gltf.materials['Frame.001']} />
        <T.Mesh geometry={gltf.nodes.Circle006_1.geometry} material={gltf.materials.USB_C_INSIDE} />
      </T.Group>
      <T.Mesh
        geometry={gltf.nodes.FrontCameraRing001.geometry}
        material={gltf.materials['CameraRIngBlack.002']}
        position={[-0.15, 19.57, -16.15]}
        scale={5.8}
      />
      <T.Group position={[-11.79, -0.15, -8.3]} scale={5.8}>
        <T.Mesh geometry={gltf.nodes.Circle.geometry} material={gltf.materials['Keyboard.001']} />
        <T.Mesh geometry={gltf.nodes.Circle_1.geometry} material={gltf.materials.Key} />
        <T.Mesh geometry={gltf.nodes.Circle_2.geometry} material={gltf.materials.Touchbar} />
      </T.Group>
      <T.Mesh
        geometry={gltf.nodes.KeyboardKeyHole.geometry}
        material={gltf.materials['Keyboard.001']}
        position={[-11.79, -0.15, -8.3]}
        scale={5.8}
      />
      <T.Mesh
        geometry={gltf.nodes.RubberFoot.geometry}
        material={gltf.materials.DarkRubber}
        position={[-11.95, -0.75, 7.86]}
        scale={5.8}
      />
      <T.Group position={[0.01, -0.21, -10.56]} scale={5.8}>
        <T.Mesh geometry={gltf.nodes.Circle012.geometry} material={gltf.materials.HingeBlack} />
        <T.Mesh geometry={gltf.nodes.Circle012_1.geometry} material={gltf.materials.HingeMetal} />
      </T.Group>
      <T.Group position={[-15.03, 0.03, 0.6]} scale={5.8}>
        <T.Mesh geometry={gltf.nodes.Circle009.geometry} material={gltf.materials['Frame.001']} />
        <T.Mesh geometry={gltf.nodes.Circle009_1.geometry} material={gltf.materials.SpeakerHole} />
      </T.Group>
      <T.Group position={[12.2, 0.03, 0.6]} scale={5.8}>
        <T.Mesh geometry={gltf.nodes.Circle009.geometry} material={gltf.materials['Frame.001']} />
        <T.Mesh geometry={gltf.nodes.Circle009_1.geometry} material={gltf.materials.SpeakerHole} />
      </T.Group>
      <T.Group position={[0.01, -0.47, -10.41]} rotation={[1.31, 0, 0]} scale={5.8}>
        <T.Mesh geometry={gltf.nodes.Circle002.geometry} material={gltf.materials['Frame.001']} />
        <T.Mesh geometry={gltf.nodes.Circle002_1.geometry} material={gltf.materials.HingeMetal} />
        <T.Mesh geometry={gltf.nodes.Circle002_2.geometry} material={gltf.materials.ScreenGlass} />
        <T.Mesh geometry={gltf.nodes.Circle002_3.geometry} material={gltf.materials.Rubber} />
        <T.Mesh geometry={gltf.nodes.Circle002_4.geometry} material={gltf.materials.DisplayGlass} />
        <T.Mesh
          geometry={gltf.nodes.AppleLogo000.geometry}
          material={gltf.materials['AppleLogo.004']}
          position={[0, -0.11, -1.8]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.58}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
