<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 model.gltf --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/model-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[0, 1.56, 0]}>
      <T.Mesh geometry={gltf.nodes.Circle038.geometry} material={gltf.materials['FrameGrey.001']} />
      <T.Mesh geometry={gltf.nodes.Circle038_1.geometry} material={gltf.materials['Front.001']} />
      <T.Mesh geometry={gltf.nodes.Circle038_2.geometry} material={gltf.materials['Antennaline.001']} />
      <T.Mesh geometry={gltf.nodes.Circle038_3.geometry} material={gltf.materials['BackGrey.001']} />
      <T.Mesh geometry={gltf.nodes.Circle038_4.geometry} material={gltf.materials['Rubber.001']} />
      <T.Mesh
        geometry={gltf.nodes.AntennaLineBottom001.geometry}
        material={gltf.materials['Antennaline.001']}
        position={[0, -2.68, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.AntennaLineTop001.geometry}
        material={gltf.materials['Antennaline.001']}
        position={[0, 0.02, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.AppleLogo001.geometry}
        material={gltf.materials['AppleLogo.001']}
        position={[0.17, 0.52, -0.08]}
      />
      <T.Mesh
        geometry={gltf.nodes.BackCameraBottomGreyRing001.geometry}
        material={gltf.materials['BackCaneraGrayRIng.002']}
        position={[0.7, 0.88, -0.09]}
      />
      <T.Mesh
        geometry={gltf.nodes.BackCameraTopGreyRing001.geometry}
        material={gltf.materials['BackCaneraGrayRIng.002']}
        position={[0.7, 1.18, -0.09]}
      />
      <T.Mesh
        geometry={gltf.nodes.BackCameraBottomLens001.geometry}
        material={gltf.materials['Lens.001']}
        position={[0.7, 0.88, -0.08]}
      />
      <T.Mesh
        geometry={gltf.nodes.BackCameraTopLens001.geometry}
        material={gltf.materials['Lens.001']}
        position={[0.7, 1.18, -0.08]}
      />
      <T.Mesh
        geometry={gltf.nodes.BackCameraP1001.geometry}
        material={gltf.materials['Black.015']}
        position={[0.7, 1.03, -0.09]}
      />
      <T.Mesh
        geometry={gltf.nodes.CameraBump001.geometry}
        material={gltf.materials['Frame.001']}
        position={[0.7, 1.04, -0.08]}
      />
      <T.Mesh
        geometry={gltf.nodes.FlashBG001.geometry}
        material={gltf.materials['PinkFlash.002']}
        position={[0.71, 1.03, -0.09]}
      />
      <T.Mesh
        geometry={gltf.nodes.FrontCameraContainer001.geometry}
        material={gltf.materials['FrontCameraBlack.002']}
        position={[0.34, 1.32, 0.08]}
      />
      <T.Mesh
        geometry={gltf.nodes.FrontSpeakerBG001.geometry}
        material={gltf.materials['FrontSpeaker.001']}
        position={[0.16, 1.32, 0.08]}
      />
      <T.Mesh
        geometry={gltf.nodes.iPhoneLogo001.geometry}
        material={gltf.materials['iPhoneLogo.001']}
        position={[0.2, -1.18, -0.08]}
      />
      <T.Mesh
        geometry={gltf.nodes.MuteSwitch001.geometry}
        material={gltf.materials['FrameGrey.001']}
        position={[-0.65, 0.92, 0.01]}
      />
      <T.Group position={[0.97, 0.56, 0]}>
        <T.Mesh geometry={gltf.nodes.Circle032.geometry} material={gltf.materials['FrameGrey.001']} />
        <T.Mesh geometry={gltf.nodes.Circle032_1.geometry} material={gltf.materials['Frame.001']} />
      </T.Group>
      <T.Group position={[0.98, -0.04, 0]}>
        <T.Mesh geometry={gltf.nodes.Circle031.geometry} material={gltf.materials['Black.014']} />
        <T.Mesh geometry={gltf.nodes.Circle031_1.geometry} material={gltf.materials['FrameGrey.001']} />
      </T.Group>
      <T.Mesh geometry={gltf.nodes.SCREEN.geometry} material={gltf.materials['Display.002']} />
      <T.Mesh
        geometry={gltf.nodes.VolumeButtons001.geometry}
        material={gltf.materials['FrameGrey.001']}
        position={[-0.66, 0.21, 0]}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
